import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Footer from "./HomepageComponents/Footer";
import Navigation from "./Navbar/Navigation";
import Head from "next/head";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth" >
      <Head>
      <link
            rel="preload"
            href="https://fonts.googleapis.com/css2?family=Jost:wght@500&display=swap"
            as="font"
            type="font/woff2"
            // crossorigin="anonymous"
          />
      <link rel="preload" href="/images/bg-image-hd.jpg" as="image"/>

      </Head>
      <body className="overflow-x-hidden " >
        <Navigation/>
        {children}
        <Footer/>
      </body>
    </html>
  );
}
